### ISSUE TITLE
Compare against original tuya firmware

### ISSUE THREAD

**Issue by Suxsem** [Suxsem/TS0202-PIR-Sensor-Zigbee-firmware#1]
Please provide a dump of the original tuya firmware in order to compare it to mine.

To do so, download repository https://github.com/Suxsem/Telink-Zigbee-serial-flash-tool
Connect the board as shown here: https://github.com/Suxsem/Telink-Zigbee-serial-flash-tool#connections
Execute `Telink_Tools.py -p COM3 read_flash 0 1048576 dump.bin` replacing COM3 with your serial port.
Upload the generated dump.bin file here.

Thank you!

**Comment by Ctrl-F4** [comment]
See https://pvvx.github.io/TS0202_TZ3000/ for FullFlash bin.

**Comment by Dreyk007** [comment]
> See https://pvvx.github.io/TS0202_TZ3000/ for FullFlash bin.

@Suxsem 
Isn't that what you're looking for?
Do I still need to do a dump?

**Comment by Suxsem** [comment]
Oh I didn't know it was already done! Thank you! I'm going to flash back the original firmware and see if problems start to happen again.

**Comment by Ctrl-F4** [comment]
Also have this device which seems to work ok.
It is easy to lower the  "occupied" state to 2 seconds when you solder the ON TIME pad on the pcb to ground.

![zp 01](https://github.com/Suxsem/TS0202-PIR-Sensor-Zigbee-firmware/assets/48384485/e841d62e-f386-47da-a095-e117d093d556)

Btw pvvx is also developing [excellent firmware ](https://github.com/pvvx/ZigbeeTLc) for this device.

**Comment by GuessWho101010** [comment]
> Also have this device which seems to work ok. It is easy to lower the "occupied" state to 2 seconds when you solder the ON TIME pad on the pcb to ground.
> 
> ![zp 01](https://private-user-images.githubusercontent.com/48384485/287065848-e841d62e-f386-47da-a095-e117d093d556.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMzgzNjksIm5iZiI6MTczNjAzODA2OSwicGF0aCI6Ii80ODM4NDQ4NS8yODcwNjU4NDgtZTg0MWQ2MmUtZjM4Ni00N2RhLWEwOTUtZTExN2QwOTNkNTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA1VDAwNDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2OGRkMjMwZWIwZDM4ODM3NzEzN2Y0OWU1OTNiNWQ5ZGVkNTljZWU4OGY1MTAzNTFmNjI4YzZmOTc2Y2JhZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pyJDDdU3CRKrOETJEQsjev5ExcfccrMiJZcrDyhFs-s)
> 
> Btw pvvx is also developing [excellent firmware ](https://github.com/pvvx/ZigbeeTLc) for this device.

I have a bit different variant of this device TS0202 _TZ3000_tqj7fiv7. It already has 2-3 seconds occupancy timeout as default. Unfortunately. I am not able to extend it to 60sec that I need.

Would you know how to extend the OnTime to 60 seconds?

(https://github.com/Koenkk/zigbee2mqtt/issues/25371?utm_source=chatgpt.com?utm_source=chatgpt.com)
